### ISSUE TITLE
Key shortcuts for tools/sending

### ISSUE THREAD

**Issue by n1ru4l** [apclary/dungeon-revealer#132]
Would be nice to have some shortcuts for the available tools. They should not clash with the key mappings provided by `react-easy-panzoom` (https://github.com/mnogueron/react-easy-panzoom#key-mapping).

**Comment by thorgod** [comment]
I like this idea, it would be nice to have the ability to switch quickly.

The main thing I do is switch between Hide/Reveal/Send
Switch between Move and Brush.

**Comment by thorgod** [comment]
If we using the center wheel it would be nice to enable zooming and panning on the DM Screen then switch back to Drawing. (Or holding shift or something)

**Comment by n1ru4l** [comment]
@thorgod any ideas on which keys should do what? This can be easily implemented, the hardest part is deciding on which keys should trigger which action 😅

**Comment by thorgod** [comment]
@n1ru4l Just some ideas. 

---I think will be used the most---
1. Holding down middle button should enable panning. (After release switch back to whatever was selected before)
2. Mouse Wheel Scroll should always Zoom in and Out.
3. Hitting shift once, should switch between Reveal/Hide Mode.
4. **Ctrl+S** Saves+Push
5. **Ctrl+Z** Undo  (Probably a new feature for a Undo/Redo Stack)
6. **Ctrl+Y** Redo

---Bellow are optional---

7. **Ctrl+N** New Map 
8. **Ctrl+M** (Map Menu)
9. **Ctrl+B** Brush
10. **Ctrl+A** Shroud all or hide all (Based on Reveal/Hide)
11. Tab (Toggle between tools->Need to switch courser hand)
12.    **Number1** (Select tool Area)
13.  **Number2** (Select tool Brush)
14.  **Number3** (Select tool Marker)
15.  -/+ Increase decrease tool size or switch marker
16. Arrow keys move map around.

**Comment by thorgod** [comment]
When in brush mode.

ctrl+drag draw rectangle.
