### ISSUE TITLE
dm-area: reduce the amount of used canvases

### ISSUE THREAD

**Issue by n1ru4l** [apclary/dungeon-revealer#148]
Currently, there are three canvases which have quite some impact on performance (especially when zooming/dragging).

When removing the cursor & fog canvas from the DOM I notice a significant performance improvement.
I am pretty sure this is caused by the transparency/absolute positioning of the different stacked canvases.

We can definitely move the cursor stuff onto the object SVG. However, I am still unsure about the shadow canvas. Maybe we can merge both the map and shadow canvas.

I am as always open for suggestions 🤔

**Comment by n1ru4l** [comment]
I experimented with [OffscreenCanvas](https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas) in #146 (5d909fb5594cad4a597df7c343c2c86bda3138ad). 

The performance is much better with only having one canvas with one SVG layer on top. As the next step, I will move all cursor related stuff to the SVG layer which also enables high-resolution cursors when zooming into the map.

**Comment by thorgod** [comment]
It would be fun to experiment with GLSL (WebGL) to do the rendering instead. (Use that GPU)
