### ISSUE TITLE
Suggestion - Multiple maps

### ISSUE THREAD

**Issue by fguillod** [apclary/dungeon-revealer#15]
Hi apclary !

First, thank you so much for this tool ! It is really simple and efficient, and fits exactly my needs as a DM !

Here is a suggestion to make the tool even more cool. Could you add multiple maps support ? For dungeons with multiple levels, for example, it would be awesome if the DM could switch back and forth between maps, saving the currently cleared area of the maps.

**Comment by thorgod** [comment]
I like this idea, and will be working on a solution to it. I need this for my game.

**Comment by n1ru4l** [comment]
I have already played around with persisting the fog across page reloads using the localstorage. However I think that would not be the ideal solution when we implement this

I think the following features are crucial:

## Create new map 
  - Name it
  - Uplod Image

## Show Available Maps

Self explanatory 

## Delete Map

Self explanatory 

## Persist Map Fog State Across Website Reload/ Map switch 

e.g. by switching back and forth between two maps

Alongside with the uploaded map image we can store a fog image that will also be loaded when a map is loaded. When the user draws (or reveals) something, the fog image should be updated.

## Create map folders (optional)

I would probably even go further by allowing the dm to create folders in which he can put different maps. Makes organizing things easier.

**Comment by thorgod** [comment]
I agree.
So splitting it into channels. FOG Channel +Grid Channel + Map Channel
Saving the channels into there respected folder. (maybe using the map name as the key.)
(all files generated)
- -Data [Folder]
    dm-setting.json [Selected map, and other settings]
    - Map [Folder]
      - bigmap.jpg [Image]
      - sea.json [URL to youtube or URL image]
   - FoW [Folder]
      - bigmap.svg
      - sea.svg
   - Meta[Folder]
      - bigmap.json [Grid or meta info]
      - sea.json [Grid  or meta info]

**Comment by n1ru4l** [comment]
WIth map folders, I was actually referring to the DM interface where he can put maps into different directories. E.g. all floors of a building or campaign.

For storing the maps on the filesystem I would recommend the following system:

- data
  - dm-settings.json
  - maps
    - [UNIQUE IDENTIFIER 1] (should be generated for each map)
      - meta.json (display name in UI, grid info, group it belongs to)
      - map.(jpeg|png|svg|whatever)
      - fog.png
    - [UNIQUE IDENTIFIER 2] (should be generated for each map)
      - meta.json (grid, map title)
      - map.(jpeg|png|svg|whatever)
      - fog.png
    -  ...

**Comment by apclary** [comment]
I like @n1ru4l 's architecture, it seems to be resilient and adaptable to further changes. The meta.json file could be expanded for other settings such as whether the canvas should render gridlines onto it or not.

**Comment by thorgod** [comment]
I agree, that sounds good. One thought unique ID could just be the map name or title to keep it simple, but I am open to whatever. (I just don't want to write code to traverse a file system to find what the map name is in the meta.json, or worse keep track of the GUIDs)

I think first pass would be good to start getting the 3 channels/layers down between DM and Player (and in sync). 

Layer 0 - Background
Layer 1 - Grid (Empty for now)
Layer 2 - FoW 
.... Design it so it will be easy to add layers/channels later. 
Layer X

**Comment by n1ru4l** [comment]
I do not like folder names with spaces and mixed lowercase and uppercase 😅, also you will have to consider special character encoding and so on. I think using some unique generated ID (like the `uuid/v4` module) is the simplest approach. We will have to traverse the file system either way 🤔

**Comment by thorgod** [comment]
Sure we can go with GUID.  Just putting my input that's all. :thinking:

I am focusing the channels/layers currently.  I don't step on your shoes.

**Comment by n1ru4l** [comment]
@thorgod FYI I started on some stuff here: https://github.com/apclary/dungeon-revealer/compare/master...n1ru4l:feat-multiple-maps

The Backend endpoints do already work, however, I did not implement the UI for creating/updating/showing multiple maps

**Comment by thorgod** [comment]
Looking good. Someones been busy working on this! =)

I am pretty busy, haven't had the motivation after work to code more. My next session D&D is the 14th after, I play I usually have more motivation to code.
