### ISSUE TITLE
pull request incoming

### ISSUE THREAD

**Issue by aaronmyhre** [apclary/dungeon-revealer#16]
Hi Apclary -

Not sure if you are actively working on dungeon-reveler, but I had a few ideas for improvements that I worked on today. 
1. added an option for a square option to the fow cursor 
2. added an outline to the fow cursor

I am still debugging an issue with the square cursor, some funky behavior due to the reliance on lineWidth and lineCap that I am trying to debut. You can checkout my repo here: https://github.com/aaronmyhre/dungeon-revealer

Anyways, just thought I would send you a heads up to see if you are interested in a pull request. 

Aaron

**Comment by apclary** [comment]
Once you figure out the bug let me know and I'll be happy to pull your
changes

**Comment by aaronmyhre** [comment]
ok cool. creating a drawing path for the square mask is actually quite a bit more complicated than I anticipated ... either I am inventing a whole new branch of geometry, or I am doing it the most painful way imaginable. 

should be done in a day or so, ill update you then.

**Comment by apclary** [comment]
Closing out due to age.
