### ISSUE TITLE
brush indicator is displaced from actual cursor position

### ISSUE THREAD

**Issue by cgebe** [apclary/dungeon-revealer#18]
The brush indicator is displaced from the actual cursor position. About 300px left and 100px up.

**Comment by apclary** [comment]
I wonder if this was introduced from the last pull which added the square
cursor. What device, browser, etc. are you using to replicate?

**Comment by cgebe** [comment]
hey i'm on lenovo thinkpad e560, firefox. i'm appending a screen shot. for the other issue as well ;)

**Comment by cgebe** [comment]
![screenshot_2016-09-09_23-31-51](https://cloud.githubusercontent.com/assets/9108142/18403592/f68a6ab6-76e5-11e6-97b4-d0ffcc08228a.png)

**Comment by cgebe** [comment]
and btw. awesome app!! :D

**Comment by wesleymccloy** [comment]
Ran into the same issue in Chrome. Seems to be both a scaling issue with the pointer and there is a dead zone where you can't use the brush as cgebe mentioned

**Comment by wesleymccloy** [comment]
I didn't pull any changes and it seems to have resolved itself when relaunching.

**Comment by hhromic** [comment]
hi guys, I made a pull request fixing this issue (at least for Chrome).
Check PR #25 .  You can clone my repository with the fix too if you wish.
Cheers!

**Comment by cgebe** [comment]
awesome
