### ISSUE TITLE
Windows executable silently exits

### ISSUE THREAD

**Issue by maxb2** [apclary/dungeon-revealer#182]
Since [v1.2.0](https://github.com/apclary/dungeon-revealer/releases/tag/v1.2.0) the Windows executable silently exits without starting the server software. There aren't any error messages. I tested the executables on a Windows 10 machine. The last version that works is [v1.1.0](https://github.com/apclary/dungeon-revealer/releases/tag/v1.1.0).

**Comment by n1ru4l** [comment]
@maxb2 could you please investigate this? I have no windows machine.

**Comment by maxb2** [comment]
I can try doing a bisection to find the bad commit.

**Comment by n1ru4l** [comment]
Might be related: https://github.com/zeit/pkg/issues/737

We should probably pin the pkg version

Lets also finally add a yarn.lock file to this repository.

**Comment by maxb2** [comment]
The bisection was failing for all commits because the build was using pkg@4.4.0. I tried pkg@4.3.7 and pkg@4.3.8 and the build worked just fine. I would suggest pinning pkg@4.3.8 until it's fixed.
