### ISSUE TITLE
large images cannot be cleared at the bottom

### ISSUE THREAD

**Issue by cgebe** [apclary/dungeon-revealer#19]
When using large images, the brush is not applicable in the bottom region. It seems like there is a cut where the brush stops working.

**Comment by cgebe** [comment]
![screenshot_2016-09-09_23-41-05](https://cloud.githubusercontent.com/assets/9108142/18403769/179d515e-76e7-11e6-9eee-ea078fdf2a04.png)

**Comment by hhromic** [comment]
hi, I made a pull request fixing a resizing issue. Check PR #25 .
Perhaps it also fixes this issue for you (I suspect it might be related).
You can clone my repository with the fix too if you wish.
Cheers!

**Comment by cgebe** [comment]
@hhromic Much appreciated, i will try it out!

**Comment by apclary** [comment]
Great job guys! I'm on vacation but I'll try to approve the pull request
soon

**Comment by cgebe** [comment]
@hhromic works!! Thank you very much
