### ISSUE TITLE
Shadow Brush not working

### ISSUE THREAD

**Issue by wesleymccloy** [apclary/dungeon-revealer#21]
Currently, in Chrome, shadow brush feature is not working.

**Comment by aaronmyhre** [comment]
I developed and tested all of the square brush stuff on chrome, so it's
weird it's not working. Can you refresh and see if that fixes it? Can you
also open chrome tools console and see if it's throwing errors?

**Comment by wesleymccloy** [comment]
I tried again today. And it seems to be working fine. This was in the same browser and everything
