### ISSUE TITLE
Brush sizing inconsistent step size

### ISSUE THREAD

**Issue by wesleymccloy** [apclary/dungeon-revealer#22]
I enlarged the brush then shrunk it and got a small brush instead of the medium one. The medium sized brush can no longer be accessed as enlarging goes to big size and shrinking goes to small size.

(In Chrome)

**Comment by apclary** [comment]
Hmm OK sounds like I need to set up a working environment and fix all of
these little issues that are popping up. Feel free to add feature requests.

**Comment by wesleymccloy** [comment]
seems to be working after trying again. Must have been a weird state
