### ISSUE TITLE
Select area to reveal fog

### ISSUE THREAD

**Issue by n1ru4l** [apclary/dungeon-revealer#36]
On Roll20 you can reveal the fog area by selecting an area via click drag release. 

This would be an useful addition for revealing huge quadratic shapes without having to click the increase brush size button for ages.

In addition to that, this feature would improve the usability on tablets where you do not have a cursor and therefore cannot exactly say how large the revealed area from the brush will be.

I will work on this feature.

**Comment by apclary** [comment]
Nice, I honestly thought other apps like Roll20 as you mentioned would have invalidated the need for this. I'd be curious to find out why people still want to use this over Roll20. Hopefully I can help you guys soon, I am still stuck in work for the US gov.

**Comment by n1ru4l** [comment]
@apclary roll20 is bloated, requires an active internet connection and has bad UX. Evaluated it but backed out after I could not simply upload a picture (file size limit) and create a map out of it. I just need a smiple tool that I can use to reveal a map to my players.
