### ISSUE TITLE
Use a frontend framework

### ISSUE THREAD

**Issue by n1ru4l** [apclary/dungeon-revealer#40]
The UI can become quite complex with all the planned features. Maybe a frontend framework could help improve the overall quality of this project. We do not have to instantly rewrite everything, we could start by introducing it for one of the new features and do stuff step by step. Having to update the DOM manually after state changes are actually annoying to me since I cannot remember when I last worked without a library like react, ember or vue.

**Comment by thorgod** [comment]
I was thinking the same thing. I wonder how one of those frameworks would benefit. (Currently most of the code is around the canvas) Is it worth the time to switch over to framework?  I have not used react, ember or vue before so have no clue about the effort. 

I do love writing in typescript! (Angular 7 what I use, I would not suggest it unless we are writing an enterprise app)

**Comment by apclary** [comment]
I’ve used React. We could use one of the create react app or similar engines to bootstrap a basic application and then migrate the pug files to jsx. I also like Redux.

**Comment by apclary** [comment]
It appears there are some libraries that let you render a canvas in react, but I am not sure how you would store the brush strokes. Maybe an array of splines? But I tend to think that's an overcomplexity.

**Comment by thorgod** [comment]
Just a note: The person who created https://www.photopea.com/ (https://github.com/photopea/photopea) would probably have some pretty good input @photopea on our application. Dungeon revealer is a super super simple mask+image. 
![image](https://user-images.githubusercontent.com/13910170/56753585-b774da80-673f-11e9-835d-617b49bb356d.png)
