### ISSUE TITLE
Delete and/or exclude large images from build

### ISSUE THREAD

**Issue by apclary** [apclary/dungeon-revealer#43]
The size of the images folder makes the source code and resulting docker images larger than they need to be.

Referenced in #29

**Comment by apclary** [comment]
I deleted the unused images, except for the large one because I noticed the app image was not large enough for some monitor sizes. If I am able to test with 4k it may turn out that we even need the XLarge but if so I'll retrieve it.

**Comment by thorgod** [comment]
Thanks!
