### ISSUE TITLE
Remove inaccurate installation instructions

### ISSUE THREAD

**Issue by apclary** [apclary/dungeon-revealer#49]
The longer instructions are no longer valid

**Comment by n1ru4l** [comment]
Yeah we should probably have a link to the releases page and a docker usage description (in the Readme.md). Everything else can be moved into a Contributing.

**Comment by n1ru4l** [comment]
Yeah we should probably have a link to the releases page and a docker usage description (in the Readme.md). Everything else can be moved into a Contributing.
