### ISSUE TITLE
Setup automated dependency updates

### ISSUE THREAD

**Issue by n1ru4l** [apclary/dungeon-revealer#62]
We can use https://depfu.com/

Depfu will create pull requests for bumping the dependencies versions.

A repository admin will have to add the depfu integration: https://github.com/apps/depfu/installations/new

**Comment by apclary** [comment]
I added this, thanks.

**Comment by apclary** [comment]
Also, it possible to add you as an admin?

**Comment by n1ru4l** [comment]
@apclary Sure, you can go for it in the repository settings!

**Comment by apclary** [comment]
I wasn't able to figure it out - from what I can tell this is only possible with Github Enterprise.

**Comment by n1ru4l** [comment]
@apclary You could set up an organization (which is free for open source) and transfer this repository over to the organization. https://github.com/account/organizations/new

**Comment by n1ru4l** [comment]
@apclary We should definitely also sign up for https://github.com/features/package-registry

**Comment by n1ru4l** [comment]
@apclary Sorry for bothering you, but have you considered moving on to an organization?
