### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by nvstgt** [apclary/dungeon-revealer#87]
The documentation on the site and in the console output is incorrect. Navigating to the DM screen with only localhost:PORT will take you to the player view. You must navigate to localhost:PORT/dm to reach the DM view.

**Comment by n1ru4l** [comment]
Thank you for your feedback. Actually, in case there is no map published yet there should be link that guides to `/dm` location.

But I understand that this could be confusing.


[You can help us and further users of dungeon-revealer by sending a pull request that updates the readme document](https://github.com/apclary/dungeon-revealer/edit/master/README.md).

**Comment by maxb2** [comment]
Closed via #95
